// AUTO-GENERATED by scripts/generate-sprite-manifest.mjs — do not edit by hand.
/* eslint-disable @typescript-eslint/no-require-imports */

export type Direction8 =
  | 'east'
  | 'north-east'
  | 'north'
  | 'north-west'
  | 'west'
  | 'south-west'
  | 'south'
  | 'south-east';

/** Indexed by round(atan2(dy, dx) / (PI/4)) mod 8 — screen y grows downward, so index 1 (PI/4) is
 * south-east, not north-east. */
export const DIRECTIONS: Direction8[] = [
  'east',
  'south-east',
  'south',
  'south-west',
  'west',
  'north-west',
  'north',
  'north-east',
];

export const KNIGHT_IDLE: Record<Direction8, number> = {
  'east': require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/Idle/rotations/east.png'),
  'south-east': require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/Idle/rotations/south-east.png'),
  'south': require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/Idle/rotations/south.png'),
  'south-west': require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/Idle/rotations/south-west.png'),
  'west': require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/Idle/rotations/west.png'),
  'north-west': require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/Idle/rotations/north-west.png'),
  'north': require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/Idle/rotations/north.png'),
  'north-east': require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/Idle/rotations/north-east.png'),
};

export const KNIGHT_RUN: Record<Direction8, number[]> = {
  'east': [
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/east/frame_000.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/east/frame_001.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/east/frame_002.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/east/frame_003.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/east/frame_004.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/east/frame_005.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/east/frame_006.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/east/frame_007.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/east/frame_008.png'),
  ],
  'south-east': [
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south-east/frame_000.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south-east/frame_001.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south-east/frame_002.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south-east/frame_003.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south-east/frame_004.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south-east/frame_005.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south-east/frame_006.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south-east/frame_007.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south-east/frame_008.png'),
  ],
  'south': [
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south/frame_000.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south/frame_001.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south/frame_002.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south/frame_003.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south/frame_004.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south/frame_005.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south/frame_006.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south/frame_007.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south/frame_008.png'),
  ],
  'south-west': [
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south-west/frame_000.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south-west/frame_001.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south-west/frame_002.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south-west/frame_003.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south-west/frame_004.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south-west/frame_005.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south-west/frame_006.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south-west/frame_007.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/south-west/frame_008.png'),
  ],
  'west': [
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/west/frame_000.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/west/frame_001.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/west/frame_002.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/west/frame_003.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/west/frame_004.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/west/frame_005.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/west/frame_006.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/west/frame_007.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/west/frame_008.png'),
  ],
  'north-west': [
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north-west/frame_000.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north-west/frame_001.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north-west/frame_002.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north-west/frame_003.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north-west/frame_004.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north-west/frame_005.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north-west/frame_006.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north-west/frame_007.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north-west/frame_008.png'),
  ],
  'north': [
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north/frame_000.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north/frame_001.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north/frame_002.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north/frame_003.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north/frame_004.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north/frame_005.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north/frame_006.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north/frame_007.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north/frame_008.png'),
  ],
  'north-east': [
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north-east/frame_000.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north-east/frame_001.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north-east/frame_002.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north-east/frame_003.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north-east/frame_004.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north-east/frame_005.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north-east/frame_006.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north-east/frame_007.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_run/animations/The_character_leans_forward_into_a_steady_rhythmic/north-east/frame_008.png'),
  ],
};

export const KNIGHT_DASH: Record<Direction8, number[]> = {
  'east': [
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/east/frame_000.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/east/frame_001.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/east/frame_002.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/east/frame_003.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/east/frame_004.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/east/frame_005.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/east/frame_006.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/east/frame_007.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/east/frame_008.png'),
  ],
  'south-east': [
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south-east/frame_000.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south-east/frame_001.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south-east/frame_002.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south-east/frame_003.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south-east/frame_004.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south-east/frame_005.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south-east/frame_006.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south-east/frame_007.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south-east/frame_008.png'),
  ],
  'south': [
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south/frame_000.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south/frame_001.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south/frame_002.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south/frame_003.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south/frame_004.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south/frame_005.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south/frame_006.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south/frame_007.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south/frame_008.png'),
  ],
  'south-west': [
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south-west/frame_000.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south-west/frame_001.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south-west/frame_002.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south-west/frame_003.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south-west/frame_004.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south-west/frame_005.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south-west/frame_006.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south-west/frame_007.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/south-west/frame_008.png'),
  ],
  'west': [
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/west/frame_000.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/west/frame_001.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/west/frame_002.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/west/frame_003.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/west/frame_004.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/west/frame_005.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/west/frame_006.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/west/frame_007.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/west/frame_008.png'),
  ],
  'north-west': [
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north-west/frame_000.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north-west/frame_001.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north-west/frame_002.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north-west/frame_003.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north-west/frame_004.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north-west/frame_005.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north-west/frame_006.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north-west/frame_007.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north-west/frame_008.png'),
  ],
  'north': [
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north/frame_000.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north/frame_001.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north/frame_002.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north/frame_003.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north/frame_004.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north/frame_005.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north/frame_006.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north/frame_007.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north/frame_008.png'),
  ],
  'north-east': [
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north-east/frame_000.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north-east/frame_001.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north-east/frame_002.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north-east/frame_003.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north-east/frame_004.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north-east/frame_005.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north-east/frame_006.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north-east/frame_007.png'),
    require('../../../assets/Character/Chevalier/un_chevalier_de_jeu_video/mid_very_fast_dash/animations/Le_personnage_se_propulse_violemment_vers_l_avant/north-east/frame_008.png'),
  ],
};

/** The plain sword. The magic-imbued variant (l_epee_est_impregner) is deliberately left out for now. */
export const SWORD_SPRITE: number = require('../../../assets/Character/Chevalier/je_veux_une_epee_qui_colle_ave/je_veux_une_epee_qui_colle_ave/rotations/je_veux_une_epee_qui_colle_ave.png');
